baseURL: /
title: 5791 Chabot
description: Devenez propriétaire d'une propriété avec plus de 3000 pieds carrés d'espace, 4 chambres dont 3 à l'étage, possibilité d'une 5e au besoin. 
DefaultContentLanguage: fr

menu:
      main:
        - name: Accueil
          url: '/'
          weight: 1
        - name: Détails
          url: '#details'
          weight: 2
        - name: Photos
          url: "#photos"
          weight: 3
        - name: Visite 3D
          url: "#visite"
          weight: 4
        - name: Contact
          url: "#contact"
          weight: 5

params: 
    businessname: "5791 Chabot"
    showLanguageSelector: false #true if bilingual site - false if unilingual
    usebasin: 'https://usebasin.com/f/795712af7aed' #endpoint for forms
    googlemap: 'https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2794.4524565273778!2d-73.59081968444002!3d45.541222979101924!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x4cc9195e914bc347%3A0xb1efbc40348d5e15!2s5791%20Rue%20Chabot%2C%20Montr%C3%A9al%2C%20QC%20H2G%202S8!5e0!3m2!1sen!2sca!4v1614890005021!5m2!1sen!2sca' # Map code of Google
    visit: '5791_rue_chabot_montr_al_qc'
    gtm: 'GTM-M88G949'
    price: "$1,289,000 $"
    mls: ""
    phone: "514-238-2699"
    social:
        facebook: ''
        twitter: ''
        pinterest: ''
        instagram: ''

enableRobotsTXT: true
disableAliases: true
disableKinds:
  - categories
  - tags

sitemap:
  changefreq: monthly
  priority: 0.5
  filename: sitemap.xml

imaging:
  resampleFilter: box
  quality: 85
  anchor: smart